t=('x',2,'three',2,2)
print('My Tuple is {}'.format(t))
print(type(t))
print(t[0])
print(t.index(2))
print(t.count(2))
print("Updated in Basix for Git Demo hehe")
print("Updated for branch BasixDev")
print("Updated before merging in BasixDev folder")
